// Action Types
export const SELECT_COMPLAINT = 'SELECT_COMPLAINT';

export const COMPLAINTS_REQUEST = 'COMPLAINTS_REQUEST';
export const COMPLAINTS_SUCCESS = 'COMPLAINTS_SUCCESS';
export const COMPLAINTS_FAILURE = 'COMPLAINTS_FAILURE';