FROM kapacitor

RUN apt-get update && apt-get install -y vim python3 python3-pip python3-dev build-essential unzip
RUN pip3 install --upgrade pip
RUN curl -L -O https://github.com/influxdata/kapacitor/archive/master.zip && \
  unzip master.zip
RUN  cd kapacitor-master/udf/agent/py && \
  python3 setup.py install
RUN curl -L -O https://repo.continuum.io/archive/Anaconda3-4.4.0-Linux-x86_64.sh && chmod +x Anaconda3-4.4.0-Linux-x86_64.sh
RUN bash Anaconda3-4.4.0-Linux-x86_64.sh -b
