version: '2'
services:
  influxdb:
    image: influxdb
    volumes:
      - /mnt/data/influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"
  chronograf:
    image: chronograf
    volumes:
      - /mnt/data/chronograf:/var/lib/chronograf
    ports:
      - "8888:8888"
    links:
      - influxdb
  kapacitor:
    image: ken/kapacitor
    environment:
      KAPACITOR_HOSTNAME: kapacitor
      KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
    links: 
      - influxdb
    ports:
      - "9092:9092"
    volumes:
      - ./kapacitor-etc:/etc/kapacitor
      - ./kapacitor-output:/mnt/output
  # Define a service for using the influx CLI tool.
  # docker-compose run influxdb-cli
  influxdb-cli:
    image: influxdb
    entrypoint:
      - influx
      - -host
      - influxdb
    links:
      - influxdb
  # Define a service for using the kapacitor CLI tool.
  # docker-compose run kapacitor-cli
  kapacitor-cli:
    image: ken/kapacitor
    entrypoint: bash
    environment:
      KAPACITOR_URL: http://kapacitor:9092
    links:
      - kapacitor
    volumes:
      - ./kapacitor-etc:/etc/kapacitor
